In [2]:
import pandas as pd
import numpy as np
import sklearn as sk

In [3]:
data=pd.read_csv("/content/50_Startups.csv")

In [4]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [6]:
 from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
data['State']=le.fit_transform(data['State'])

In [9]:
data.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [13]:
y=data['Profit']
x=data.drop(columns=['Profit'],axis=1)

In [21]:
from sklearn.preprocessing import scale

In [23]:
names=x.columns

In [24]:
x=scale(x)

In [25]:
x

array([[ 2.01819092,  0.55696553,  2.18783528,  1.16731536],
       [ 1.95675646,  1.0893969 ,  1.95029024, -1.23401909],
       [ 1.75232048, -0.75766814,  1.64392865, -0.03335187],
       [ 1.54982902, -0.1132146 ,  1.43322263,  1.16731536],
       [ 1.49925539, -1.11632102,  1.28814125, -0.03335187],
       [ 1.27083396, -0.806604  ,  1.25996984,  1.16731536],
       [ 1.3319795 ,  0.93574262, -0.74312422, -1.23401909],
       [ 1.23558377,  0.87437939,  0.92787631, -0.03335187],
       [ 1.01776417,  0.99163696,  0.82340982,  1.16731536],
       [ 1.08011094, -0.48065199,  0.76691751, -1.23401909],
       [ 0.60181303, -0.4102384 ,  0.1210342 , -0.03335187],
       [ 0.57410176, -1.10165542,  0.29637694, -1.23401909],
       [ 0.4220906 ,  0.20479752,  0.29718526, -0.03335187],
       [ 0.38030758,  0.50538623,  0.32125438, -1.23401909],
       [ 1.00438367,  1.27949493,  0.35403374, -0.03335187],
       [ 0.88337621,  0.03184527,  0.39886959,  1.16731536],
       [ 0.06818346, -0.

In [26]:
x=pd.DataFrame(x,columns = names)

In [27]:
x.head()

R&D Spend  Administration  Marketing Spend     State
0   2.018191        0.556966         2.187835  1.167315
1   1.956756        1.089397         1.950290 -1.234019
2   1.752320       -0.757668         1.643929 -0.033352
3   1.549829       -0.113215         1.433223  1.167315
4   1.499255       -1.116321         1.288141 -0.033352

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [31]:
import tensorflow

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [33]:
model=Sequential()

In [35]:
model.add(Dense(units =4,kernel_initializer ="random_uniform",activation='relu'))

In [36]:
model.add(Dense(units =10,kernel_initializer ="random_uniform",activation='relu'))

In [37]:
model.add(Dense(units =12,kernel_initializer ="random_uniform",activation='relu'))

In [38]:
model.add(Dense(units =1,kernel_initializer ="random_uniform"))

In [40]:
model.compile(loss='mse',metrics=['mse'],optimizer="adam")

In [42]:
model.fit(x_train,y_train,epochs=5,batch_size=10)

Epoch 1/5
9/9 [==============================] - 1s 3ms/step - loss: 13930791936.0000 - mse: 13930791936.0000
Epoch 2/5
9/9 [==============================] - 0s 4ms/step - loss: 13930789888.0000 - mse: 13930789888.0000
Epoch 3/5
9/9 [==============================] - 0s 3ms/step - loss: 13930786816.0000 - mse: 13930786816.0000
Epoch 4/5
9/9 [==============================] - 0s 3ms/step - loss: 13930781696.0000 - mse: 13930781696.0000
Epoch 5/5
9/9 [==============================] - 0s 5ms/step - loss: 13930775552.0000 - mse: 13930775552.0000


In [43]:
pred=model.predict(x_test)

In [44]:
pred

array([[0.09388857],
       [0.09105916],
       [0.09090573],
       [0.09169963],
       [0.09177914],
       [0.09031473],
       [0.09067672],
       [0.09230253],
       [0.09301695],
       [0.0913986 ],
       [0.09057508],
       [0.09190114],
       [0.09207165],
       [0.09230253],
       [0.09157567],
       [0.09157278],
       [0.09207165],
       [0.09182677],
       [0.09067672],
       [0.09102552],
       [0.09227417],
       [0.09111232]], dtype=float32)

In [45]:
y_test

1     191792.06
75     90708.19
46     49490.75
99    146121.95
61    110352.25
35     96479.51
86     42559.73
92    182901.99
0     192261.83
71     97427.84
70     97483.56
11    144259.40
59    118474.03
3     182901.99
26    105733.54
27    105008.31
20    118474.03
56    125370.37
47     42559.73
58    122776.86
93    166187.94
29    101004.64
Name: Profit, dtype: float64

In [48]:
y_test=np.array(y_test)

In [50]:
error=(y_test-pred)

In [51]:
error

array([[191791.96611143,  90708.09611143,  49490.65611143,
        146121.85611143, 110352.15611143,  96479.41611143,
         42559.63611143, 182901.89611143, 192261.73611143,
         97427.74611143,  97483.46611143, 144259.30611143,
        118473.93611143, 182901.89611143, 105733.44611143,
        105008.21611143, 118473.93611143, 125370.27611143,
         42559.63611143, 122776.76611143, 166187.84611143,
        101004.54611143],
       [191791.96894084,  90708.09894084,  49490.65894084,
        146121.85894084, 110352.15894084,  96479.41894084,
         42559.63894084, 182901.89894084, 192261.73894084,
         97427.74894084,  97483.46894084, 144259.30894084,
        118473.93894084, 182901.89894084, 105733.44894084,
        105008.21894084, 118473.93894084, 125370.27894084,
         42559.63894084, 122776.76894084, 166187.84894084,
        101004.54894084],
       [191791.96909427,  90708.09909427,  49490.65909427,
        146121.85909427, 110352.15909427,  96479.41909427,
    

In [52]:
from sklearn import metrics

In [53]:
metrics.mean_squared_error(pred,y_test)

16204040247.865137